services:
  ai-comic-factory:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3000"
    environment:
      - VITE_GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - OLLAMA_API_BASE=${OLLAMA_API_BASE}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s